[package]
name = "l6t"
version = "0.1.0"
authors = ["Artem Egorkine <arteme@gmail.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayref = "0.3.6"
iff-rs = { git = "https://github.com/qpliu/iff-rs.git" , rev = "fe61c18" }
