[package]
name = "l6t-symbolic"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
file = { package = "l6t-file", path = "../file" }
