[package]
name = "l6t-info"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
clap = { version = "4", features = ["derive", "wrap_help"] }

l6t = { path = "../lib" }
